from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dasboard'),
    path('ingresos/',views.ingresos),
    path('registrarIngreso/',views.registrarIngreso),
    path('ingresos/edicionIngreso/<nIngreso>',views.edicionIngreso),
    path('ingresos/eliminacionIngreso/<nIngreso>',views.eliminacionIngreso),
    path('ingresos/editarIngreso/<int:nIngreso>/',views.editarIngreso),
    path('ingresos/detalleIngreso/<int:nIngreso>/',views.detalleIngreso),
    path('verificar-cedula/', views.verificar_cedula, name='verificar_cedula'),
    path('detallePDF/<int:nIngreso>', views.detallePDF,),
    path('descargarExcelIngresos/',views.export_to_excel,name='exportar a excel'),
    path('egresos/',views.egresos),
    path('registrarEgreso/',views.registrarEgreso),
    path('egresos/detalleEgreso/<int:nEgreso>/',views.detalleEgreso),
    path('egresos/eliminacionEgreso/<nEgreso>',views.eliminacionEgreso),
    path('egresos/edicionEgreso/<nEgreso>',views.edicionEgreso),
    path('egresos/editarEgreso/<int:nEgreso>/',views.editarEgreso),
    path('egresos/imprimirEgreso/<int:nEgreso>', views.imprimirEgreso),
    path('egresos/descargarExcelEgresos/', views.export_to_excel_egreso),
    path('facturar/',views.facturar),
    path('registrarFactura/',views.registrarFactura),
    path('obtener_precio_biologico/', views.obtener_precio_biologico, name='obtener_precio_biologico'),
    path('facturar/edicionFactura/<nFactura>',views.edicionFactura),
    path('facturar/editarFactura/<str:nFactura>/',views.editarFactura),
    path('facturar/eliminacionFactura/<nFactura>',views.eliminacionFactura),
    path('facturar/detalleFactura/<nFactura>/',views.detalleFactura),
    path('facturar/imprimirFactura/<nFactura>', views.imprimirFactura),
    path('facturar/descargarExcelFacturas/', views.export_to_excel_facturas),
    path('api/get-factura-data/', views.get_factura_data, name='get_factura_data'),
    path('mensajes/',views.mensajes),
    path('bandeja-mensajes/',views.ver_mensajes),
    path('bandeja-mensajes/detalleMensaje/<int:id>/',views.detalle_mensaje),
    path('eliminar-mensaje/<int:id>/',views.eliminar_mensaje),
    path('bandeja-mensajes/responderMensaje/<int:id>/',views.responder_mensaje),
    path('enviar/', views.enviar_correo, name='enviar_correo'),
    
]