# Generated by Django 5.1.1 on 2024-09-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('nIngreso', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transaccion', 'Transanccion'), ('cheque', 'Cheque')], max_length=20)),
                ('ciudad', models.CharField(default='San Juan Nepomuceno', editable=False, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valorIngreso', models.IntegerField(blank=True, default=0, null=True)),
                ('concepto', models.CharField(max_length=200)),
            ],
        ),
    ]
