# Generated by Django 5.1.1 on 2024-09-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0002_alter_ingresos_ningreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='valorIngreso',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
