# Generated by Django 5.1.1 on 2024-09-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0003_alter_ingresos_valoringreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='valorIngreso',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
