# Generated by Django 5.1.1 on 2024-09-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0004_alter_ingresos_valoringreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('Cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
    ]
