# Generated by Django 5.1.1 on 2024-09-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0005_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='Cedula',
            new_name='cedula',
        ),
    ]
