# Generated by Django 5.1.1 on 2024-09-17 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0006_rename_cedula_usuarios_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comite.usuarios'),
        ),
    ]
