# Generated by Django 5.1.1 on 2024-09-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0007_ingresos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='tipo_pago',
            field=models.CharField(max_length=20),
        ),
    ]
