# Generated by Django 5.1.1 on 2024-09-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0008_alter_ingresos_tipo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunadores',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Egresos',
            fields=[
                ('nEngreso', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=20)),
                ('ciudad', models.CharField(default='San Juan Nepomuceno', editable=False, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valorIngreso', models.IntegerField(blank=True, default=0, null=True)),
                ('concepto', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comite.usuarios')),
            ],
        ),
    ]
