# Generated by Django 5.1.1 on 2024-09-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0010_rename_nengreso_egresos_negreso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egresos',
            old_name='valorEngreso',
            new_name='valorEgreso',
        ),
    ]
