# Generated by Django 5.1.1 on 2024-09-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0011_rename_valorengreso_egresos_valoregreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='egresos',
            name='aprobado',
            field=models.CharField(default='Jorse Arzuaga', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='egresos',
            name='contabilizado',
            field=models.CharField(default='Eduard Posso', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='egresos',
            name='recibe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='egresos',
            name='revisado',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
