# Generated by Django 5.1.1 on 2024-09-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0012_remove_egresos_usuario_egresos_aprobado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresos',
            name='revisado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
