# Generated by Django 5.1.1 on 2024-09-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0013_alter_egresos_revisado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresos',
            name='recibe',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='egresos',
            name='revisado',
            field=models.CharField(default='Jorse Arzuaga', max_length=100),
        ),
    ]
