# Generated by Django 5.1.1 on 2024-10-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0014_alter_egresos_recibe_alter_egresos_revisado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturar',
            fields=[
                ('nFactura', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_vacunas', models.IntegerField(default=0)),
                ('lote', models.IntegerField(default=0)),
                ('laboratio', models.CharField(max_length=100)),
                ('valor_total', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comite.usuarios')),
            ],
        ),
        migrations.DeleteModel(
            name='Vacunadores',
        ),
        migrations.RenameField(
            model_name='vacunas',
            old_name='precio',
            new_name='valor_unitario',
        ),
        migrations.RemoveField(
            model_name='vacunas',
            name='stock',
        ),
        migrations.AlterField(
            model_name='egresos',
            name='aprobado',
            field=models.CharField(default='Jorge Arzuaga', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='egresos',
            name='revisado',
            field=models.CharField(default='Jorge Arzuaga', max_length=100),
        ),
        migrations.AddField(
            model_name='facturar',
            name='vacunas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comite.vacunas'),
        ),
    ]
