# Generated by Django 5.1.1 on 2024-10-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0016_alter_vacunas_valor_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturar',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
