# Generated by Django 5.1.1 on 2024-10-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0017_facturar_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturar',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
