# Generated by Django 5.1.1 on 2024-10-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0020_rename_vacunas_biologicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturar',
            name='valor_total',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
