# Generated by Django 5.1.1 on 2024-10-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0021_alter_facturar_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturar',
            name='biologico_aftosa',
        ),
        migrations.RemoveField(
            model_name='facturar',
            name='biologico_cepa19',
        ),
    ]
