# Generated by Django 5.1.1 on 2024-10-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0022_remove_facturar_biologico_aftosa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturar',
            name='biologico',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
