# Generated by Django 5.1.1 on 2024-10-30 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0023_facturar_biologico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturar',
            old_name='laboratio',
            new_name='laboratorio',
        ),
        migrations.AddField(
            model_name='facturar',
            name='informacio_biologicos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comite.biologicos'),
        ),
    ]
