# Generated by Django 5.1.1 on 2024-10-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0024_rename_laboratio_facturar_laboratorio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturar',
            old_name='informacio_biologicos',
            new_name='informacion_biologicos',
        ),
    ]
