# Generated by Django 5.1.1 on 2024-10-31 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0025_rename_informacio_biologicos_facturar_informacion_biologicos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturar',
            old_name='informacion_biologicos',
            new_name='info_biologicos',
        ),
    ]
