# Generated by Django 5.1.1 on 2024-10-31 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0026_rename_informacion_biologicos_facturar_info_biologicos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturar',
            old_name='info_biologicos',
            new_name='biologicosInformacion',
        ),
    ]
