# Generated by Django 5.1.1 on 2024-11-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0028_rename_valor_unitario_biologicos_valorunidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturar',
            name='lote',
            field=models.JSONField(),
        ),
    ]
