# Generated by Django 5.1.1 on 2024-11-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0029_alter_facturar_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturar',
            name='biologico',
            field=models.JSONField(),
        ),
    ]
