# Generated by Django 5.1.1 on 2024-11-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0030_alter_facturar_biologico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturar',
            name='biologicosInformacion',
        ),
        migrations.AddField(
            model_name='facturar',
            name='infoAftosa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_aftosa', to='comite.biologicos'),
        ),
        migrations.AddField(
            model_name='facturar',
            name='infoCepa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_cepa', to='comite.biologicos'),
        ),
    ]
