# Generated by Django 5.1.1 on 2024-11-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0032_facturar_cantidad_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturar',
            name='laboratorio',
            field=models.JSONField(),
        ),
    ]
