# Generated by Django 5.1.1 on 2024-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0033_alter_facturar_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturar',
            name='valor_total',
            field=models.BigIntegerField(default=0),
        ),
    ]
