# Generated by Django 5.1.1 on 2024-11-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0034_alter_facturar_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturar',
            name='estatus',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
