# Generated by Django 5.1.1 on 2024-11-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0035_facturar_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturar',
            name='nFactura',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
