# Generated by Django 5.1.1 on 2024-11-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0036_alter_facturar_nfactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='facturas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comite.facturar'),
        ),
    ]
