# Generated by Django 5.1.1 on 2024-11-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0038_facturar_valor_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturar',
            name='valor_pendiente',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facturar',
            name='estatus',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
    ]
