# Generated by Django 5.1.1 on 2024-11-22 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0039_facturar_valor_pendiente_alter_facturar_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturar',
            name='infoIngreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_ingresos', to='comite.ingresos'),
        ),
    ]
