# Generated by Django 5.1.1 on 2024-11-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0040_facturar_infoingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturar',
            name='infoIngreso',
        ),
    ]
