# Generated by Django 5.1.1 on 2024-11-23 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0041_remove_facturar_infoingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturar',
            name='infoIngreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_ingresos', to='comite.ingresos'),
        ),
    ]
