# Generated by Django 5.1.1 on 2025-03-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0043_remove_facturar_infoingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
