# Generated by Django 5.1.1 on 2025-03-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0044_mensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
