# Generated by Django 5.1.1 on 2025-04-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0045_alter_mensajes_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
